export const FEEDBACK = {
  i: 1,
  c: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
  text: 'Thank you for providing feedback!\nPlease share your experience to help improve our service',
  label1: 'Not likely',
  label2: 'Extremely Likely',
  layout: 'horizontal',
  'border-style': 'solid',
  'border-width': 2,
  'border-color': '#ffffff',
  'margin-right': 10,
  'font-size': 14,
  'font-weight': 'bold',
  type: 1,
  label: 1,
  'margin-bottom': 10,
  color: '#ff1d1b1b',
  'margin-left': 10,
  'font-family': 'Helvetica',
  'corner-radius': 10,
};
